brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("todo_list_list")),
        name="home",
    ),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListView,
    TodoDetailView,
    TodoCreateView,
    TodoUpdateView,
    TodoDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="todo_list_detail"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="todo_list_delete"),
    path("create/", TodoCreateView.as_view(), name="todo_list_create"),
    path("<int:pk>/edit/", TodoUpdateView.as_view(), name="todo_list_update"),
    # path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path(
        "items/create/", TodoItemCreateView.as_view(), name="todo_item_create"
    ),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="todo_item_update",
    ),
]

todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return str(self.name)


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(
        blank=True,
        null=True,
        auto_now=False,
        auto_now_add=False,
    )
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return str(self.task)

todos/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from todos.models import TodoList, TodoItem
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

# Create your views here.
class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]
    # success_url = reverse_lazy("todo_list_detail")

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/items/create.html"
    fields = ["task", "due_date", "is_completed", "list"]
    success_url = reverse_lazy("todo_list_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # def get_success_url(self):
    #     return reverse_lazy("todo_list_list")


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todos/items/edit.html"
    fields = ["task", "due_date", "is_completed", "list"]
    # success_url = reverse_lazy("todo_list_detail")

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>My Lists</h1>
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Number of items</th>
                    </thead>
                    <tbody>
                        <tr>
                            {% for todo in todo_list %}
                            <td>{{todo.name}}</td>
                            <td>{{todo}}</td>
                        </tr>
                    </tbody>
                </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create a new List</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create a new list</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                        <button class="button">Create</button>
                    </div>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>List Detail</title>
    </head>
    <body>
        <main>
            <main>
                <div class="delete-form">
                    <form method="post">
                        {% csrf_token %}
                        <h1>Are you sure you want to delete "{{ todolist.name }}"?</h1>
                        {{ form.as_p }}
                        <div>
                            <button class="button">Delete</button>
                        </div>
                    </form>
                </div>
            </main>
        </main>
    </body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>List Detail</title>
    </head>
    <body>
        <main>
            <div>
                <h1>{{ todolist.name }}</h1>
                <div>
                    <p>
                        <a href="{% url 'todo_list_update' todolist.id %}">Edit</a>
                    </p>
                </div>
                <div>
                    <p>
                        <a href="{% url 'todo_list_delete' todolist.id %}">Delete</a>
                    </p>
                </div>
                <h2>Tasks</h2>
                <table>
                    <thead>
                        <th>Task</th>
                        <th>Due date</th>
                    </thead>
                    <tbody>
                        {% for items in todolist.items.all %}
                            <tr>
                                <td>
                                    <a href="{% url 'todo_item_update' items.pk %}">{{ items.task }}</a>
                                </td>
                                <td>{{ items.due_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Update List</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Update List</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                        <button class="button">Update</button>
                    </div>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/items/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create a new List</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create a new item</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                        <button class="button">Create</button>
                    </div>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/items/delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>List Detail</title>
    </head>
    <body>
        <main>
            <main>
                <div class="delete-form">
                    <form method="post">
                        {% csrf_token %}
                        <h1>Are you sure you want to delete "{{ todolist.name }}"?</h1>
                        {{ form.as_p }}
                        <div>
                            <button class="button">Delete</button>
                        </div>
                    </form>
                </div>
            </main>
        </main>
    </body>
</html>

todos/templates/todos/items/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create a new List</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Update item</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="control">
                        <button class="button">Update</button>
                    </div>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <main>
            <div>
                <h1>My Lists</h1>
                <div>
                    <a href=" {% url 'todo_list_create' %}">Create a new list</a>
                </div>
                <br>
                <div>
                    <a href=" {% url 'todo_item_create' %}">Create a new item</a>
                </div>
                <br>
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Number of items</th>
                    </thead>
                    <tbody>
                        {% for todo in todolist_list %}
                            <tr>
                                <td>
                                    <a href=" {% url 'todo_list_detail' todo.id %}">{{ todo.name }}</a>
                                </td>
                                <td>{{ todo.items.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </body>
</html>